### ISSUE TITLE
Refactor for better Maintainability

### ISSUE THREAD

**Issue by andreasgrafen** [catppuccin/discord#12]
As mentioned by @tuhanayim in #10 it's probably a good call to refactor some of the CSS to ensure better maintainability. This could also be used to make things less likely to break in case of updates to Discord's autogenerated class names.

Instead of using hardcoded colours everywhere it would make future updatess and further development easier if the extended palette would be defined at the start of the document and later on just called on by variables.

I would also suggest to partially match class names instead of typing them out in full.
`.bar-2eAyLE, .jumpToPresentBar-1cEnH0 {}` could also be `[class^="bar-"], [class^="jumpToPresentBar-"]`.

I'll happily go through the files and apply the suggested changes. :3

**Comment by andreasgrafen** [comment]
There already is a ready made [CSS palette](https://github.com/catppuccin/palette/blob/main/Catppuccin.css) available btw. c:

**Comment by andreasgrafen** [comment]
Okay, I've just updated the [Catppuccin.theme.css](https://github.com/andreasgrafen/ctp-discord/blob/main/Catppuccin.theme.css) to use colour variables. c:

Is the second suggested change for partial class matching also wished to be implemented?

**Comment by tuhanayim** [comment]
> Is the second suggested change for partial class matching also wished to be implemented?

I think yes, but it seems to me that using partial class matching might cause conflicts.

And btw, if it's possible please delete extra and unnecessary spaces. And maybe set a formatter like Prettier? The code style should have one format IMO. Because when others contribute, it can be complex if everyone uses a different format.

**Comment by andreasgrafen** [comment]
> I think yes, but it seems to me that using partial class matching might cause conflicts.

In which cases would you think it would cause issues?
I've not been too deep into the dev tools, but it seems like there aren't any duplicates that are only differentiated by the randomised string part. I might be wrong tho.

> And btw, if it's possible please delete extra and unnecessary spaces.

Probably a good idea, you're right!
I'd at least leavie it in a tabular structure for the HSL value declaration to make future changes for colours easier if there ever are some, but the rest should be no problem to compress. _Tho.. it looks ugly imo. :D_

**Comment by tuhanayim** [comment]
And instead setting color variables as root, maybe use a preprocessor like SASS. Setting color variables as SASS variable and changing `.dark-theme` variables to these variables will make CSS code shorter. But using SASS can cause a few problems.

1. We need to building SASS code when committing.

- This can be done with Git hooks. When committing, if the built CSS is not updated, it can prevent commiting.
- Or maybe Github Actions. When a PR or commit comes, push built CSS to another branch, or release to Releases page.

But this theme is just a color scheme. Using SASS might be overkill for such a theme.

**Comment by andreasgrafen** [comment]
Introducting SASS is super overkill imo – it adds a lot of mostly unnecessary overhead. I personally don't see much of an issue with globally setting these variables.. Yes, technically it's polluting the global space, but this allows for easier extension in the future. I also don't see the possibility of this clashing with something of Discords original code.
Since everything is served from the users local machine there also isn't much of a reason to consider bundle size, I think.

**Comment by tuhanayim** [comment]
> In which cases would you think it would cause issues?

First of all, I don't know about `div[class^="blabla"]` thingies. I may be wrong.

Lets say there's two classes, named `coolCard-1` and `coolCard-2`. Using `div[class^="coolCard"]` *probably* will select both classes. I don't know Discord's CSS whether uses same classes with different keys, but if its, it maybe cause a problem 🤔

**Comment by tuhanayim** [comment]
> Introducting SASS is super overkill imo – it adds a lot of mostly unnecessary overhead. I personally don't see much of an issue with globally setting these variables.. Yes, technically it's polluting the global space, but this allows for easier extension in the future. I also don't see the possibility of this clashing with something of Discords original code. Since everything is served from the users local machine there also isn't much of a reason to consider bundle size, I think.

Okay then. Time to change classes with matchers!

**Comment by andreasgrafen** [comment]
> Lets say there's two classes, named `coolCard-1` and `coolCard-2`. Using `div[class^="coolCard"]` _probably_ will select both classes. I don't know Discord's CSS whether uses same classes with different keys, but if its, it maybe cause a problem 🤔

Yeah, in that case it will select both of these. o far I haven't come across a case like this. It's probably smart do also further increase spcificity by doing something like `#thingy [class^="wrapper"] > [class^="coolCard"]` to avoid as much potential crosscontamination as possible.

**Comment by tuhanayim** [comment]
Then, I agree with replacing classes with matchers.

**Comment by andreasgrafen** [comment]
What's your stance on this @WitherCubes? c:

**Comment by WitherCubes** [comment]
> What's your stance on this @WitherCubes? c:

Anything is fine for me. :)

**Comment by andreasgrafen** [comment]
Yeah.. I give up on the whole partial class matchting thing. The more I've been digging though discords markup.. the more I'm concerned for my sanity. I really hope that their development code is not as weirdly structured when it comes to repeating class names and stuff. This is waay harder than I would have initially thought, and there is leakage everywhere and the partial matching requires a lot of handling edgecases. I don't think  it's worth the effort anymore.

**Comment by WitherCubes** [comment]
This is the reason why I didn't take this approach in the first place.

**Comment by andreasgrafen** [comment]
I'll bow to your wisdom. I'm clearly to eager. :'D
_Might sound sarcastic, but isn't meant to be._

**Comment by WitherCubes** [comment]
#13 is merged, so this issue is now closed.
