### ISSUE TITLE
Unthemed Elements 

### ISSUE THREAD

**Issue by skinatro** [catppuccin/discord#129]
![image](https://user-images.githubusercontent.com/60423203/217062732-f28a97b6-e1d7-42f8-9024-ef3b3ccc3ff4.png)

This section of the discord is not themed yet

**To Reproduce**
it is the #home channel in the `TCMSecurity server`
the [invite link](discord.gg/tcm) to reproduce

**Comment by rubyowo** [comment]
i don't see anything wrong here?
