### ISSUE TITLE
Found an unthemed section or broken styling? Report issues here.

### ISSUE THREAD

**Issue by nekowinston** [catppuccin/discord#131]
This issue is to track all the minor problems with the theme.

Please upload a good screenshot in comments, that:
- Uses the latest version of **this repository**
- Shows the problem
- Clearly shows the context (which panel, submenu, etc.), or mention it in your comment
- Use arrows / pointers if it's a minor issue, just to be explicit what is meant

Problems that impact readability will be higher priority, our goal here isn't to fully theme every nook and cranny of Discord. If it's a *really minor issue*, it likely will only get fixed if people provide CSS to fix it.

**Comment by InvitedToHell** [comment]
![image](https://user-images.githubusercontent.com/73737531/219096708-c37e063f-cc45-4fd2-be9b-1c8dcbef85bb.png)

As you can see here, the bar that displays the badges is broken due to the profile theming feature of discord nitro. 

A fix for this would be the following:
Remove this part from the css

`div[class*=layerContainer] > div[class*=layer] div[class*=header] {
  background: #181825;
}`

**Comment by RoootTheFox** [comment]
(using discord canary)
![image](https://user-images.githubusercontent.com/78933889/219512697-9e49cdda-5486-45f7-887f-5ab582c1b342.png)
![image](https://user-images.githubusercontent.com/78933889/219512749-7baff2a2-5625-4657-9ac1-f9de9148445a.png)

Pretty much all user status indicators are broken because discord changed their fill color for status indicators

**Comment by RoootTheFox** [comment]
I've opened a PR that addresses both issues mentioned above: #138

**Comment by rubyowo** [comment]
![image-21.png](https://user-images.githubusercontent.com/105302757/220175932-5ddb13a1-c52d-48f8-831c-b47e0dc946ad.png)

![image-28.png](https://user-images.githubusercontent.com/105302757/220175937-82916bef-88f9-4517-9cb4-8293cce76b59.png)

![20-231.jpeg](https://user-images.githubusercontent.com/105302757/220175934-6c5e23c3-55e2-438d-b79e-d44fb9850f19.jpeg)

![image-26.png](https://user-images.githubusercontent.com/105302757/220175935-e49eb97e-5d5a-4809-b67d-2eadb14348d9.png)

![image-30.png](https://user-images.githubusercontent.com/105302757/220175936-72bde0e3-f85e-4fff-81e6-b84ce82cebf0.png)

![18-212.jpeg](https://user-images.githubusercontent.com/105302757/220175938-2052566d-5f64-45ac-81b8-1275c1ac022b.jpeg)

**Comment by rubyowo** [comment]
`.removeAttachmentHoverButton-3gHROs:hover, .keyboard-mode .removeAttachmentHoverButton-3gHROs:focus` the attachment delete button's text when hovered on.

**Comment by Sourcastic** [comment]
![Screenshot_20230224_211132](https://user-images.githubusercontent.com/79325941/221229771-fa4d80e8-0846-4e97-8cbe-adb5531d3c27.png)

The text when searching for a server to join is barely readable.

**Comment by sgoudham** [comment]
![image](https://user-images.githubusercontent.com/58985301/221362190-9ef82a46-2d12-458f-be92-cb940cefbad3.png)

:eyes: Think I'm using either Blue or Sky as my accent colour

**Comment by rubyowo** [comment]
Known issue. I might fix it if i want to, but as a popup, it atmost appears once and never again 🤷‍♀️

**Comment by RoootTheFox** [comment]
When enabling developer mode (the same thing that allows access to the experiments tab) there's a tab called "Dismissible Contents" that allows you to make those popups appear again

![image](https://user-images.githubusercontent.com/78933889/221377633-e4423408-af4d-4ef3-b2e1-6b1a962500a7.png)

- class for the header text color: `.upsellTooltipHeader-28hJ7J`
- classes of the popup body text: `text-sm-normal-AEQz4v content-3aT_vH`
- parent element/container classes of the "Got it" and "Set up" buttons: `upsellButtonsContainer-1RUYlp upsellButtonsAdjacent-1tzhoa`
- classes of the "set up" button: `button-ejjZWC lookInverted-2GrLaB colorBrand-2M3O3N sizeMedium-2oH5mg grow-2T4nbg`

HTML if needed or something:
```html
<div id="popout_227" class="theme-dark layer-2aCOJ3" style="position: absolute; left: 145px; top: 42.1619px;"><div class="animatorBottom-L63-7D translate-PeW1wK didRender-2SiRlm"><div><div class="message-1oQ5HY upsellTooltipWrapper-1wqikQ caretTopCenter-1wqGIE"><div class="container-1wopa7"><div class="card-zRPyMF"><div><div class="wrapper-1VLyxH" role="img" aria-label="AutoMod" aria-hidden="false" style="width: 40px; height: 40px;"><svg width="40" height="40" viewBox="0 0 40 40" class="mask-1FEkla svg-2azL_l" aria-hidden="true"><foreignObject x="0" y="0" width="40" height="40" mask="url(#svg-mask-avatar-default)"><div class="avatarStack-3vfSFa"><img src="/assets/e7af5fc8fa27c595d963c1b366dc91fa.gif" alt=" " class="avatar-b5OQ1N" aria-hidden="true"></div></foreignObject></svg></div></div><div class="content-3hLy03"><div class="name-1ux7iw"><div class="text-sm-semibold-S5fJwz nameText-23M5LK" data-text-variant="text-sm/semibold" style="color: var(--text-brand);">AutoMod</div><svg class="shield-2XlvF_" aria-hidden="true" role="img" width="16" height="16" viewBox="0 0 24 24"><path d="M12 1L3 5V11C3 16.55 6.84 21.74 12 23C17.16 21.74 21 16.55 21 11V5L12 1ZM12 11.99H19C18.47 16.11 15.72 19.78 12 20.93V12H5V6.3L12 3.19V11.99Z" fill="hsl(200, calc(var(--saturation-factor, 1) * 100%), 49.4%)"></path></svg></div><div class="spoiler-1T2VP4"></div></div></div></div><h2 class="defaultColor-1EVLSt heading-md-semibold-2h_vsp defaultColor-1GKx81 upsellTooltipHeader-28hJ7J" data-text-variant="heading-md/semibold">Custom Messages from AutoMod</h2><div class="text-sm-normal-AEQz4v content-3aT_vH" data-text-variant="text-sm/normal" style="color: white;">Add a note to educate members whenever AutoMod blocks their message in <strong>AutoMod ➜ Block Message ➜ Edit</strong></div><div class="upsellButtonsContainer-1RUYlp upsellButtonsAdjacent-1tzhoa"><button type="button" class="button-ejjZWC lookFilled-1H2Jvj colorBrand-2M3O3N sizeMedium-2oH5mg grow-2T4nbg"><div class="contents-3NembX">Got it</div></button><button type="button" class="button-ejjZWC lookInverted-2GrLaB colorBrand-2M3O3N sizeMedium-2oH5mg grow-2T4nbg"><div class="contents-3NembX">Set up</div></button></div></div></div></div></div>
```

**Comment by sgoudham** [comment]
**Where:**The pop-up box when I go to change someone's nickname

**Screenshot**:
![image](https://user-images.githubusercontent.com/58985301/224121704-fee3ecf2-c363-4f8e-ba74-41c630b357d0.png)

**Comment by sbeve72** [comment]
![image](https://user-images.githubusercontent.com/65838896/236509621-b65c02db-1e00-432f-9d0d-d397c2a26a41.png)
This section that pops up when you go to edit your username

**Comment by he3als** [comment]
Incorrectly colored streamer mode and general popups.

![Discord_tgKToodrt6](https://github.com/catppuccin/discord/assets/65787561/87caba3d-796a-42df-8695-f22f88b5382f)

**Comment by he3als** [comment]
Incorrectly coloured
![image](https://github.com/catppuccin/discord/assets/65787561/417a9d7f-1f62-4a84-9ca8-ebfbaeedebbf)

**Comment by hollowshiroyuki** [comment]
Hi !
Spotify activity is not readable in the user profile and in user cards :

![image](https://github.com/catppuccin/discord/assets/35398794/ad32734d-2e58-4061-9a3d-dd0357809b46)
![image](https://github.com/catppuccin/discord/assets/35398794/9ad10483-16a7-451a-aac3-33e7d7346060)

**Comment by Mixaz017** [comment]
![image](https://github.com/catppuccin/discord/assets/31244102/661b080a-e8fd-4693-bca1-ef34390d424f)
The chat close button in voice channels have a wrong background color when the layout is in overlapping mode (when the window width is too small to show both participants and the text chat at the same time)

**Comment by NotAShelf** [comment]
the new members tab seems broken
![image](https://github.com/catppuccin/discord/assets/62766066/df07651c-09d9-447b-8bb3-f53c28a62d29)

**Comment by ToxicAven** [comment]
@NotAShelf could you explain how to access this menu? I believe it may be one of discords random sample experiments, as I can't find a way to access it.

**Comment by NotAShelf** [comment]
It's randomly rolled to servers, I believe only a select 25% can access it now.

**Comment by ToxicAven** [comment]
Hm, i'm not in a server with this, could you add me on discord @toxicaven and send me a server with it enabled?
