### ISSUE TITLE
Theme does not work on WebCord

### ISSUE THREAD

**Issue by MathisP75** [catppuccin/discord#136]
Other themes work, but for some reason the catppuccin themes do not.

**Comment by rubyowo** [comment]
could you provide more info? such as how you installed the theme

**Comment by MathisP75** [comment]
1. I get the `mocha.theme.css` from the repo
2. I put it in the `Themes` folder of WebCord
3. I run `webcord --add-css-theme=.config/WebCord/Themes/mocha.theme.css`
4. The theme should be applied automatically, as it did with another theme I tried, but it's not the case for the catppuccin theme.

The theme that worked is https://github.com/Roboron3042/Cyberpunk-Neon/tree/master/CSS/discord

**Comment by rubyowo** [comment]
can reproduce here.
I've used webcord with the ctp theme in the past and it has worked, not sure what's up now.

**Comment by rubyowo** [comment]
AH. it fetches the raw github page??????
![image](https://user-images.githubusercontent.com/105302757/218776967-e1f4268f-ed2d-4116-a2f9-bb31de91e72d.png)

**Comment by rubyowo** [comment]
wait no that was my skill issue

**Comment by rubyowo** [comment]
yeah no i was being stupid, it doesn't happen to me

**Comment by MathisP75** [comment]
Wait, so it works for you?

**Comment by rubyowo** [comment]
it does indeed.
```bash
echo "@import url("https://catppuccin.github.io/discord/dist/catppuccin-mocha.theme.css");" > mocha.theme.css
webcord --add-theme-css ./mocha.theme.css
webcord
```

**Comment by MathisP75** [comment]
Oh, for some reason it worked with your command, thanks!

**Comment by uncomfyhalomacro** [comment]
I seem to have this issue for the flatpak variant
