### ISSUE TITLE
Suggestions for the theme

### ISSUE THREAD

**Issue by rubyowo** [catppuccin/discord#143]
# Have a suggestion for the port? Suggest them here!
> **Note** <br>
> It's not guaranteed that they'll be implemented in the port.

Provide a clear and concise idea, and even an image (if you can) of what you want added.

**Comment by Tnixc** [comment]
![image](https://user-images.githubusercontent.com/85466117/226153572-30d52573-88ca-468e-b9f9-25a72fc02a3a.png)
![image](https://user-images.githubusercontent.com/85466117/226153576-287b06de-3485-45f9-82af-7c2c54f97101.png)
Clownboard, community icons to stay consistent

**Comment by rubyowo** [comment]
@nekowinston 🤡

**Comment by tsukki9696** [comment]
Maybe add a way to change accent colors

**Comment by nekowinston** [comment]
@tsukki9696 
> Maybe add a way to change accent colors

```
/* You can also append Catppuccin colors to customize the accent, e.g. */
/* mocha (pink accent)*/
@import url("https://catppuccin.github.io/discord/dist/catppuccin-mocha-pink.theme.css");
/* frappe (maroon accent) */
@import url("https://catppuccin.github.io/discord/dist/catppuccin-frappe-maroon.theme.css");
```
