### ISSUE TITLE
No META found

### ISSUE THREAD

**Issue by Bamboooz** [catppuccin/discord#155]
![image](https://user-images.githubusercontent.com/83116089/228875151-4ff8c7da-6502-4f76-8145-e0bcafd2d688.png)

I downloaded the frappe theme, put it in themes and this popped out, what have i done wrong?

**Comment by rubyowo** [comment]
what injector are you using?

**Comment by Bamboooz** [comment]
better discord

**Comment by Bamboooz** [comment]
and i solved it already by just restarting discord, anyways thanks for help
