### ISSUE TITLE
CI currently succeeds in spite of syntax errors in the stylesheets

### ISSUE THREAD

**Issue by nyxkrage** [catppuccin/discord#163]
See [successful CI job for f5e73f2](https://github.com/catppuccin/discord/actions/runs/4646396166/jobs/8222792192) where there are clearly errors in the "Run yarn release" step (a missing comma)

**Comment by nyxkrage** [comment]
I think this is happening because `yarn release` ends up using the exit code of the last command that being `rm src/catppuccin-*-*.theme.scss`, which obviously will not fail.

**Comment by nekowinston** [comment]
Should be fixed, ty!
