### ISSUE TITLE
Spoilered Text Heavily Blends With Mentioned Message Background

### ISSUE THREAD

**Issue by steviegt6** [catppuccin/discord#18]
![DiscordCanary_txFfmKkQUo](https://user-images.githubusercontent.com/27323911/169681818-292fb025-c6a6-4fab-9007-87423872aced.gif)
This is especially inconveniencing with the spoiler is trailing the end of a message, and it's not immediately obvious that it's there.

**Comment by nekowinston** [comment]
I hope this is fixed with 2414d77b9a36dda361b6bc0bef3a3eb0e87f81a5, please feel free to re-open this issue if it's still too low contrast.
