### ISSUE TITLE
Channel Icons

### ISSUE THREAD

**Issue by Starry-Tacos** [catppuccin/discord#186]
In [preview.webp](https://raw.githubusercontent.com/catppuccin/discord/main/assets/preview.webp), I saw that the channel icons were colored, and I don't know if this is a existing feature or just in the photo.

**Comment by Starry-Tacos** [comment]
Just FYI, the channels are arranged like this:
`div > div > div > ::before + div > svg`

**Comment by rubyowo** [comment]
Icons have been removed due to discord adding channel emoiis themself.
