### ISSUE TITLE
New messages indicator is gray instead of red

### ISSUE THREAD

**Issue by D3SOX** [catppuccin/discord#20]
I think those should be red (and were before)

![image](https://user-images.githubusercontent.com/24937357/180272190-48bee30f-f6ce-4081-bd9f-894fdb968357.png)
![image](https://user-images.githubusercontent.com/24937357/180272247-8ecb1131-21fd-4d62-a577-791b0e9bef03.png)

**Comment by nekowinston** [comment]
fixed with 2414d77b9a36dda361b6bc0bef3a3eb0e87f81a5, it uses your accent colour now.
