### ISSUE TITLE
Using the `dev` branch with Discocss

### ISSUE THREAD

**Issue by fufexan** [catppuccin/discord#22]
How can I use the `dev` branch with Discocss? It doesn't have a theme selector, and I don't know what I have to modify in order to make it select one of the themes.

**Comment by nekowinston** [comment]
Hi there! :wave:

We'll use a custom tool to generate Discord themes to the user's liking, it just hasn't been moved to the Catppuccin org yet. You can find it here, in the meanwhile: https://catppuccin-discord-customizer.vercel.app

I'll add a couple more features, such as automatic syncing between 2 flavours depending on the OS dark/light theme.

**Comment by fufexan** [comment]
Oh, that sounds great! Thanks!
