### ISSUE TITLE
Css not working with better discord

### ISSUE THREAD

**Issue by n6v26r** [catppuccin/discord#232]
The css recently stopped working with better-discord. The dark themes simply don't do anything. Frappe and Latte only partially theme the app. (Only the top bar)

Other stylesheets also fail.
Is it a discord thing?

**Comment by Tnixc** [comment]
Reinstall betterdiscord

**Comment by Maritsu** [comment]
doesn't work for me too; using `betterdiscordctl reinstall` did nothing  

using catppuccin mocha theme

**Comment by Tnixc** [comment]
Yup, better discord css injection is broken atm

**Comment by ToxicAven** [comment]
This seems more like a betterdiscord problem than a css problem

**Comment by Nekosis** [comment]
@ToxicAven This was posted in announcements in their Discord:

![2023-10-25_18-43](https://github.com/catppuccin/discord/assets/37462865/7e875b1c-9ac3-45b9-86dc-2016017a3b21)

**Comment by ToxicAven** [comment]
The theme is fully functional again @Nekosis. It is still a better discord issue, as the theme will not break your client.
