### ISSUE TITLE
Most parts of Discord have reverted to default colors as of 2022-08-10

### ISSUE THREAD

**Issue by V13Axel** [catppuccin/discord#24]
Basically the entire app has reverted to default colors, using Stylus on Firefox:

![2022-08-10_07-52](https://user-images.githubusercontent.com/2779682/183894730-3d5ca23a-e1c1-4d7e-b815-2a9b2d0f27a0.png)

Certain parts are still partially themed, but it looks like a significant update was released that has broken the theme.

**Comment by nekowinston** [comment]
Are you on the `dev` branch or `main`?

**Comment by V13Axel** [comment]
I was originally on the `main` branch, but upon switching to the CSS available in `dev`, I see no difference even after a complete uninstall/reinstall of the style and a relaunch of the browser.

However, I can confirm that it _does_ seem to work correctly in Stylus on Google Chrome. The most interesting tidbit, to me, is that I tried Firefox on Windows just now and it worked fine! I'm running Firefox 103.0 on Linux and Firefox 103.0.2 on the Windows machine - I can't imagine a point-release causing such a big difference, but I'll update and report back.

**Comment by V13Axel** [comment]
Update: I thought I was going crazy, as I updated to the latest Firefox on Linux and it was still showing me old colors. 

I tried a full refresh with Ctrl+F5, tried uninstall/reinstall of Stylus, and wasn't ultra-sure where to go next apart from disabling my other extensions until one was a smoking gun... and it was the extension Dark Reader. Sorry about the confusion!

**Comment by nekowinston** [comment]
No worries, I'm hoping to finally get Catppuccin Discord 0.2.0 finished next week, by the way
