### ISSUE TITLE
Update CSS classes for broken Better Discord

### ISSUE THREAD

**Issue by 42Willow** [catppuccin/discord#240]
The latest discord update stuffs up all the css classes, etc. so almost everything isn't working.

![image](https://github.com/catppuccin/discord/assets/70784752/1682eef8-c9e7-4201-aff1-f17d03b9613b)
sourced from better discord server

**Comment by nekowinston** [comment]
It looks like this is only broken on BetterDiscord for some reason, I'll link to [our Discord where we discussed this](https://discord.com/channels/907385605422448742/1020555849372012635/1166934368707686420).

**Comment by 42Willow** [comment]
Yep it works, I already prefer openasar over BD. I'll leave this issue open though, as the readme only has instructions for better discord - and it seems these themes will need to be updated for it.

**Comment by ToxicAven** [comment]
Betterdiscord needs to update around themes, not themes need to update around better discord. Until betterdiscord cleans up their act or even makes quite literally importing a css file work, it is unsupported. Use openasar.

**Comment by nekowinston** [comment]
@ToxicAven if it's unsupported for now, it might be wise to remove it from the README/tell people about that there.

**Comment by ToxicAven** [comment]
Good idea, I'll fix that shortly.
