### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Tnixc** [catppuccin/discord#255]
<img width="668" alt="image" src="https://github.com/catppuccin/discord/assets/85466117/1a536a6b-c6ad-466f-8c71-84441e6e7457">
<img width="256" alt="image" src="https://github.com/catppuccin/discord/assets/85466117/082881d9-0f03-42dc-bbda-257461773229">

Nitro settings page

<img width="782" alt="image" src="https://github.com/catppuccin/discord/assets/85466117/7fc21589-6553-4051-bed8-e78de3f19517">

That gradient border

<img width="1189" alt="image" src="https://github.com/catppuccin/discord/assets/85466117/b6da940f-5c87-4869-8ad3-6107678455a3">

Server boost:

<img width="1142" alt="image" src="https://github.com/catppuccin/discord/assets/85466117/da7f7e4b-4b1c-44fb-867c-fac31b4f6ee8">

Beta badges

<img width="685" alt="image" src="https://github.com/catppuccin/discord/assets/85466117/c50c98c4-d401-4a49-a74f-a3ccdd5e6ad9">

That underline on hover in what's new

<img width="412" alt="image" src="https://github.com/catppuccin/discord/assets/85466117/4f798584-bffa-4c4a-bf35-d12d844953de">

Text color:

<img width="390" alt="image" src="https://github.com/catppuccin/discord/assets/85466117/805bbdaf-5fd7-4ff6-a801-b138ae1dd176">

**Comment by Tnixc** [comment]
Most of the nitro gradient borders are also not themed

**Comment by ToxicAven** [comment]
taking it easy on me today i see

**Comment by Tnixc** [comment]
<img width="197" alt="image" src="https://github.com/catppuccin/discord/assets/85466117/f1ebbb5c-0a00-41b0-afc4-b03376b8d411">

Jump to present loading thingy

<img width="769" alt="image" src="https://github.com/catppuccin/discord/assets/85466117/1c83c6ee-89c7-4e02-940b-9b3a77024cf7">

**Members page bottom background:**
<img width="539" alt="image" src="https://github.com/catppuccin/discord/assets/85466117/76e9ab72-559b-432d-b74e-a23b49b9d82f">


Brief unthemed section when hovering over super reactions

https://github.com/catppuccin/discord/assets/85466117/502ec8c0-b758-4faa-9003-71cb543878c7

**Comment by ToxicAven** [comment]
Fixed in #256
