### ISSUE TITLE
Catppuccin 0.2.0

### ISSUE THREAD

**Issue by o-farag** [catppuccin/discord#28]
Are there any plans to support different color schemes? At the moment only Catppuccin-Dark is supported, but I'm also interested in other schemes like Latte or Frappe. Could these be added? Is there a way to copy the css from somewhere else if I wanted to do it manually?

**Comment by nekowinston** [comment]
Hi there, thanks for your issue!

You can find the current progress for 0.2.0 (Latte, Frappe, Macchiato, Mocha) on the [dev branch](https://github.com/catppuccin/discord/tree/dev).

If you want CSS for inclusion in BetterDiscord/Goosemod, etc. Please check out the [Discord Customizer](catppuccin-discord-customizer.vercel.app/).

I'll keep this issue open to track the Update to 0.20

**Comment by fufexan** [comment]
@nekowinston I just went and tried to use the Customizer site, but when I click on "show compiled CSS" it spews out "Error 500 - Internal Server error".

Also using the theme which `@import`s a URL, also doesn't work.

**Comment by nekowinston** [comment]
I'm sorry yeah, we're dealing with some deployment issues.
The whole Customizer still works when run locally, but can't be run inside Docker or on Vercel. It's an annoying issue we'll have to sort out. 🤔  

I'll update this issue when the Customizer works again, apologies for breaking the deployed version.

**Comment by fufexan** [comment]
Got you. Do you have the source available somewhere?

**Comment by nekowinston** [comment]
Yeah, it's available here: https://github.com/nekowinston/ctp-discord-customizer

The issue is that `node_modules/stylus/lib/functions/index.styl` can't be found when running inside Docker, or on Vercel...
I'm happy to accept any PR fixing that; in the meantime you can just get it running locally by `yarn build && yarn dev`

**Comment by nekowinston** [comment]
Closed with 2414d77b9a36dda361b6bc0bef3a3eb0e87f81a5, the Customizer is still a TODO, which I'll try to get to in the coming days.
