### ISSUE TITLE
Forum overview background no longer gets themed

### ISSUE THREAD

**Issue by Insprill** [catppuccin/discord#282]
As of a recent Discord update, the overview background of forum channels no longer gets themed.
![image](https://github.com/catppuccin/discord/assets/52843537/668b74f1-8ba2-41f9-b4ae-901a212b5a63)

**Comment by Mylloon** [comment]
Another example of the issue using Latte:

![image](https://github.com/catppuccin/discord/assets/29067904/bb526a42-6dcf-4fba-b8ed-482ad6f43bf8)
