### ISSUE TITLE
Unreadable spotify artist - song name (Latte)

### ISSUE THREAD

**Issue by RoverBot-Dev** [catppuccin/discord#286]
![image](https://github.com/catppuccin/discord/assets/68994821/6412f397-a429-4898-ba31-d8b46dfb74c4)
The spotify listening status artist name and song name arent readable in light mode + latte theme

**Comment by ToxicAven** [comment]
Seems to not be broken for me, can confirm this is still a problem?

**Comment by RoverBot-Dev** [comment]
not sure but i think it has something to do with discord nitro's custom profile colors? 
![image](https://github.com/catppuccin/discord/assets/68994821/6825afcc-7a9a-478c-9a66-bee7c66f15cb)
if i disable Sync profile themes in accessibility settings, this happens with a custom profile color in Mocha.

**Comment by ToxicAven** [comment]
Due to the same reason as #298, profile payout theming is probably not going to be fixed for a little longer
