### ISSUE TITLE
Does not anymore with Stylus.

### ISSUE THREAD

**Issue by aspizu** [catppuccin/discord#287]
It just doesn't work, even after reinstalling or restarting.

`Firefox Developer Edition 125.0b6 (64-bit)`

`@version        0.2.1`

**Comment by rubyowo** [comment]
Does it work in a different browser

**Comment by aspizu** [comment]
Tried on chrome and it does work.

**Comment by isabelincorp** [comment]
Strange, I have a similar setup but with the normal version of Firefox, do other user styles work with that version of Firefox?

**Comment by aspizu** [comment]
my own user style works but only the catppuccin one doesn't do anything
