### ISSUE TITLE
Considerable slowdown

### ISSUE THREAD

**Issue by orxngc** [catppuccin/discord#293]
When using Discord (I use Vesktop, if this is relevant) mocha slows everything down, a _lot_. After enabling, switch channels takes a solid half a second, while disabled it's more like a quarter of a second.
Is there something in the theme that's slowing things down? I'm pretty sure it should only be changing colors, so I'm not sure why this would happen.

**Comment by ToxicAven** [comment]
It is just changing colors, I've personally never seen this case but it seems to be most prevalent on Vesktop.

**Comment by orxngc** [comment]
Hm, alright. I'm going to install and try Armcord later today and see if there's a difference.
