### ISSUE TITLE
user's profile ui is broken

### ISSUE THREAD

**Issue by somerand0mcat** [catppuccin/discord#298]
i clicked on a user's profile and the profile ui breaks 
![image](https://github.com/catppuccin/discord/assets/147266582/9142bf5f-5f76-4464-8b4a-ba76e747c8c7)
however on profiles with a gradient background it doesn't break
![image](https://github.com/catppuccin/discord/assets/147266582/91dc9d10-62ef-4004-a088-9c7d363673aa)

i tried it with different catppuccin flavors, still doesn't solve the issue

**Comment by ToxicAven** [comment]
Try turning on Sync Profile Colors in the settings.

**Comment by somerand0mcat** [comment]
> Try turning on Sync Profile Colors in the settings.

still doesnt work
![image](https://github.com/catppuccin/discord/assets/147266582/55914b24-80c5-4e76-b1e3-cd1282ee8a28)

**Comment by uncenter** [comment]
> Try turning on Sync Profile Colors in the settings.

Pretty sure we already know it is a Discord beta thing based on what I've seen in the Discord.

**Comment by ToxicAven** [comment]
Yea, I'll fix it after work tonight.

**Comment by somerand0mcat** [comment]
> Pretty sure we already know it is a Discord beta thing based on what I've seen in the Discord.
yeah i think its already on the discord channel

**Comment by somerand0mcat** [comment]
> Yea, I'll fix it after work tonight.

nice

**Comment by ToxicAven** [comment]
So here is the conundrum with this issue. The issue being experienced here is a result of discord only giving some people access to random experiments, of which I and likely many others do not have yet. As it will likely be a replacement for the current one, it also shares many of the same classes with the current one. Fixing the new one would likely break the old one, so for now, I am going to hold off on fixing this. If you have the new profile, you can force your discord not to use it by setting the `Simplified Profile Experiment` experiment to `Control Bucket` using a client mod.

**Comment by somerand0mcat** [comment]
oh alright
