### ISSUE TITLE
Call popups don't get themed

### ISSUE THREAD

**Issue by Niru2169** [catppuccin/discord#301]
(I'm using Vesktop and I've added the raw link to the css file as mentioned in the readme.) The call popup chat isn't themed...

**Comment by ToxicAven** [comment]
could you provide a screenshot or otherwise? they are not broken on my end.

**Comment by Niru2169** [comment]
![image](https://github.com/catppuccin/discord/assets/66010447/9ddcd3fd-2d7e-4fe0-852a-74bd059ff057)
it didn't work in Discord client either
this is my current setting
![image](https://github.com/catppuccin/discord/assets/66010447/9d5e076d-3e2e-414f-858f-aeb93cf71fc8)

**Comment by ToxicAven** [comment]
This is a problem with Vencord, not the theme. Vencord does not extend its themes to this extra popout. There is nothing we can do about this from the themes perspective.
