### ISSUE TITLE
Theme code readability concerns.

### ISSUE THREAD

**Issue by WinnerWind** [catppuccin/discord#310]
The code which is imported in the theme is unreadable and hence modifying it is quite difficult. Moreover, as the themes here are light-mode/dark-mode only themes, trying to make a "hybrid" theme (Eg. Latte in light mode but Mocha in dark mode) is impossible due to the aforementioned restriction.
Would it be possible to clean up the code so that is is more readable and hence more editable?

**Comment by ToxicAven** [comment]
Are you referring to the minified code that is provided for importing?

**Comment by WinnerWind** [comment]
Yes, I am!
Personally it would be nice if it was more readable, as dumping it all into one line is *horrible* for readability and debugging.

I'm trying to make a version of this theme that can both use Latte and Mocha at the same time, so Latte in light mode, and Mocha in dark mode, however because of how unreadable the import code is, I can't figure out from where to where I should dump it into the `.theme-light` and `.theme-dark` classes.

**Comment by ToxicAven** [comment]
The minified code loads a fair bit faster than the unminified version. If you wish to have the unminified code, please clone the repo and use the `yarn build` task to get an unminified copy of the code for debugging.

**Comment by WinnerWind** [comment]
Thanks for the tip! I just gave it a try, and indeed, an unminified version of the theme was outputted in `<root>/dist/dist`
This will come in handy for me. Thanks so much, and sorry for the trouble.
