### ISSUE TITLE
Powercord Support

### ISSUE THREAD

**Issue by brandao07** [catppuccin/discord#37]
So today, i noticed Powercord was no longer detecting Catppuccin as a theme and i can't find it anymore on this repo. Is it no longer being maintained?

**Comment by rubyowo** [comment]
https://github.com/catppuccin/discord#goosemod--clients-with-custom-css-support

**Comment by nekowinston** [comment]
Hi there :wave:
Yeah seeing how Powercord is EOL, we won't provide the `powercord.manifest` anymore.
