### ISSUE TITLE
Low contrast between read and unread channels/threads

### ISSUE THREAD

**Issue by afnzmn** [catppuccin/discord#44]
![image](https://user-images.githubusercontent.com/47723802/192178949-ef5db43b-36a1-4ae5-979d-5518b090384d.png)
![image](https://user-images.githubusercontent.com/47723802/192179010-126ca854-526d-4db8-b7ac-fd46519bdbc5.png)

**Comment by isabelincorp** [comment]
I find the contrast fine enough, but soon enough we will be opening a site that will allow you to turn off rainbow threads entirely.

**Comment by afnzmn** [comment]
Well I would disagree, the current contrast makes me think read channels have unread messages. 

What I think should happen is to lower the opacity/darken the read channels to something like this:
![image (34)](https://user-images.githubusercontent.com/47723802/192181200-7e605a00-b95e-4f94-bffe-add8110c4c0c.png)

**Comment by isabelincorp** [comment]
Or maybe have the thread text normal text like the normal channels, then unread is the subtle rainbow like we currently have.

**Comment by isabelincorp** [comment]
^ (New account ignore this message)

**Comment by nekowinston** [comment]
I've fixed the thread unread colours, please re-open the issue if you think that this issue persists.
![image](https://user-images.githubusercontent.com/79978224/192420360-3f7dca89-f83e-48f9-bf8d-1c3f59508c94.png)
![image](https://user-images.githubusercontent.com/79978224/192420434-e572a1d3-2b5e-4446-95d0-db624a20b74e.png)
