### ISSUE TITLE
GooseMod ending support

### ISSUE THREAD

**Issue by ProudNoob** [catppuccin/discord#46]
![Screenshot grabbed from GooseMod's discord](https://user-images.githubusercontent.com/7321641/192491251-910a723a-b427-4de0-9702-52bff575cf0b.png)

GooseMod's main dev just declared its abandonment, will we end our support of it just like Powercord?

**Comment by isabelincorp** [comment]
When Goosemod can no longer be injected/Custom CSS doesn't work, I think we should remove it from the readme.

**Comment by 21zz** [comment]
Ducko is planning to add custom CSS support to OpenAsar which is not affected by Discord's recent changes

![Ducko's message](https://i.imgur.com/sqkmxla.png)
