### ISSUE TITLE
Text Colours

### ISSUE THREAD

**Issue by andreasgrafen** [catppuccin/discord#5]
While background colours are aligned with Catppuccin, text colours don't seem to be? This is especially noticable for the grey text in both the channel and user overview. Tho the text colour for chat messages is the default too, if I'm not mistaken.

The text selection colour would also be a nice little accent, if it can be changed. c:

**Comment by DonutDev** [comment]
Personally I just assumed the default colors look visible and good. If you have any Catppuccine colors to use instead of the default ones for text, give them here!

**Comment by andreasgrafen** [comment]
I'd use white for all basic Text like in messages, and different shades of the grey (and maybe the light black) colours for the more muted colours.

**Comment by WitherCubes** [comment]
Issues still needed to be resolved:
- Text color in some places (settings, channels, members, etc.).

Issues fixed:
- Text colors changed in some places.
- Selection foreground and background
