### ISSUE TITLE
Menu items invisible

### ISSUE THREAD

**Issue by killjoy1221** [catppuccin/discord#52]
With the latte theme via BetterDiscord, the menu items are invisible or have a very low contrast to the background. This does not effect menu items from right clicking a message, as they are using a dark theme (which is probably its own issue).

![image](https://user-images.githubusercontent.com/3409962/197342008-6a5dc546-7347-4870-9422-8c82f433ba1b.png)

Switching discord's appearance settings to a light theme appears to be a workaround for both.

**Comment by ToxicAven** [comment]
That is because the light theme expects you to be using discord light mode.

**Comment by ToxicAven** [comment]
This should probably be marked as wontfix.

**Comment by Askath** [comment]
Maybe it would be a nice idea to at that info into the install guide in the Readme.

**Comment by rubyowo** [comment]
Added a FAQ for this in #120
