### ISSUE TITLE
Status Colours

### ISSUE THREAD

**Issue by andreasgrafen** [catppuccin/discord#6]
I'm not sure of that's even possible easily; I'm just going by what I did for the Revolt port.
I think it would be nice to tweak the colours of User-Statuses to match Catppuccin. The default colours are really vibrant and kinda clash with the purple-ish backgrounds. o:

**Comment by WitherCubes** [comment]
As mentioned on discord, the status colors, when changed to the catppuccin colorscheme looks ugly not attractive.
