### ISSUE TITLE
SASS rewrite breaks Stylus (throws TypeError)

### ISSUE THREAD

**Issue by raluvy95** [catppuccin/discord#61]
The title says all. I was trying to update Catppuccin theme which expects to work. 
Sadly, this doesn't do anything since the entire CSS code is replaced with `@import url("...")`.
I copied compiled CSS into Stylus editor and I got an error:

```
stylus:1088:47
   1084|   box-shadow: inset 0 1px 0 #313244;
   1085|   -webkit-box-shadow: inset 0 1px 0 #313244;
   1086| }
   1087| .theme-light > div[class^=focusLock] > div[class^=root] {
   1088|   box-shadow: 0 0 0 1px #313244, 0 2px 10px 0 hsla(0, calc(var(--saturation-factor, 1) * 0%), 0%, 0.1);
-------------------------------------------------------^
   1089|   -webkit-box-shadow: 0 0 0 1px #313244, 0 2px 10px 0 hsla(0, calc(var(--saturation-factor, 1) * 0%), 0%, 0.1);
   1090| }
   1091| .theme-light[class*=profileColors-] [class*=userTagUsernameBase-],

TypeError: expected "saturation" to be a unit, but got literal:calc(var(--saturation-factor, 1) * 0%)
    at ".theme-light > div[class^=focusLock] > div[class^=root] " (stylus:1088:1)
```

anyway, I use Mozilla Firefox 106.0.5

**Comment by rubyowo** [comment]
cannot reproduce here, could you provide more info please?
![image](https://user-images.githubusercontent.com/105302757/200181857-558eb1b7-5b66-44e0-a8b8-92a4e254e09c.png)
Firefox v106.0.5 on archlinux linux 6.0.2-zen here

**Comment by rubyowo** [comment]
Yeah you can ignore the curly bracket error, doesn't actually effect anything. Though I'm curious as to why the CSP blocks it

**Comment by rubyowo** [comment]
Hello there again, I have no info. Under the options in stylus, there's a setting under "Advanced" named "Patch CSP to allow style sheets", this lil setting here would ease the CSP allowing the theme to load.
I'll add this here to the README so this probably wont happen again
