### ISSUE TITLE
New App Directory Page not themed

### ISSUE THREAD

**Issue by justTOBBI** [catppuccin/discord#68]
It appears a new feature, the App Directory, has rolled out. And of course it's not themed yet.
I can provide more info if needed :)

![catppuccin ftw](https://user-images.githubusercontent.com/47004621/201088041-5eeb06cc-3eb0-4cb5-863b-0e6f284bf722.png)

**Comment by rubyowo** [comment]
... huh? I literally just fixed it tho

**Comment by justTOBBI** [comment]
Wait I thought I updated the theme, but maybe it didnt update.

**Comment by rubyowo** [comment]
![image.png](https://user-images.githubusercontent.com/105302757/201088681-d7812014-73d3-4c8a-8b89-a9bddaf9b83e.png) how it should look

**Comment by Sourcastic** [comment]
I can confirm, it is fixed for me as well.
