### ISSUE TITLE
UI State Colours

### ISSUE THREAD

**Issue by andreasgrafen** [catppuccin/discord#7]
Some UI Elements are missing styling. This includes indicators like the »more unread messages« bar on the channel list, as well as things like the indicator that you're reading older messages, and the »there are new messages« bars in the main chat window.

I'd also include mentioned messages here. They seem to use the default yellow, which imo looks not too nice with the Catppuccin theme. I'd suggest maybe not even using any yellow at all, but mauve?

Some :hover and :active states also seem to be using the default grey colours instead of tweaked ones? This includes the emote picker, and channel, as well as user list.

**Comment by HannoVB1** [comment]
>  I'd suggest maybe not even using any yellow at all, but mauve?

I feel like, as a pastel coloured theme, it is mostly purple, I think a pastel pink or mauve for 'reply' would stand out quite a bit but wouldn't be a bad idea overall.

**Comment by WitherCubes** [comment]
Issue partially resolved in #9

**Comment by WitherCubes** [comment]
The only fix needed to close this issue is:
-  :hover and :active states

**Comment by HannoVB1** [comment]
Hi, just checked and i feel like now there's some inconsistency across the colours. 

Maybe we should change the jump to present button to #6E6C7E aswell.

What are your thoughts?

old:
![151679139-e394ea97-13ee-48e3-9821-6062c89a9a29](https://user-images.githubusercontent.com/98668034/152422477-af8fde67-3dc0-4ae3-aa02-0ebcd30b3f94.png)

new:
![Ca2pture](https://user-images.githubusercontent.com/98668034/152422519-d307ac5c-f808-417a-8e83-074ad3ddfe95.PNG)

to go along with:
![Capture](https://user-images.githubusercontent.com/98668034/152422511-a8aaa870-79e3-4680-a31a-2a297b542a3b.PNG)

**Comment by WitherCubes** [comment]
> What are your thoughts?

Sure, go ahead and make a PR or I will commit it after I have made other changes.

**Comment by andreasgrafen** [comment]
I think Discord has the bar in top of the message area in gray, while the one on top is blue. But I like the unification of colour suggested here as it's still easy to tell apart with the light background colour. One think I wanna throw in tho: Does the white on mid-grey pass a contrast check for readability?

**Comment by WitherCubes** [comment]
> Does the white on mid-grey pass a contrast check for readability?

I don't know because I am not able to open the devtools in the discord app and I have tried a lot of other methods to enable devtools but no luck for me right now. BTW we can't make every single change have the contrast check and the grey is dark enough for the white to be visible.

![image](https://user-images.githubusercontent.com/72592921/152466769-ec1d679b-da55-48ee-ab6c-8bd2a26ed839.png)

**Comment by andreasgrafen** [comment]
Hmm, okay. So it passes AA but **not AAA**.

That said: When you're working on a port for a UI that potentially is used by a lot of people, you should **always** keep accessibility in mind. It might be readable for you, but is it readably for someone who has visual impairments? These checks don't exist for fun.

**Comment by WitherCubes** [comment]
I agree but in that case, why does discord's default colrs fail the check:

![image](https://user-images.githubusercontent.com/72592921/152467687-e68adf45-4598-43dc-8ec5-ee6306c896a3.png)

**Comment by andreasgrafen** [comment]
Damn.. for real Discord? Now that's just sad. lol
I still think aiming for **AA** should be the way to do things. **But** I'm just leaving my opinions scattered around the internet. You're free to disagree. :D

**Comment by andreasgrafen** [comment]
Regarding things in the channel sidebar; I've been tinkering around a little and I think the best selector would probably be `#channels [role="listitem"]:hover` and I'm not sure about the active state, but maybe the selector is a place to start with?

I'll dig a bit more to hopefully be a little bit more useful in helping with this. c:

**Comment by WitherCubes** [comment]
`--background-modifier-selected:` handles the active state I guess and I have [commited it](https://github.com/catppuccin/discord/commit/3aba6fd02fdda24acea24b77a79fc1dd8865a9af).
